title: AWS.docset
description: Offline AWS documentations for Dash and Zeal
author: tzing

url: "https://docset.tzing.dev"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME

theme: minima

minima:
  date_format: "%Y-%m-%d"
  social_links:
    - platform: github
      user_url: https://github.com/tzing/dashify-aws-docs
