title: AWS.docset
description: Offline AWS documentations for Dash and Zeal
author:
  name: tzing

url: "https://page.tzing.dev/"
baseurl: "/dashify-aws-docs"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

theme: minima

minima:
  date_format: "%Y-%m-%d"
  social_links:
    - platform: github
      url: https://github.com/tzing/dashify-aws-docs
