name: Download Redshift Database Developer Guide

on:
  schedule:
    - cron: "50 18 * * 2"
  workflow_dispatch:

jobs:
  download:
    strategy:
      max-parallel: 4
      matrix:
        include:
          - lang: en_us
            sitemap: https://docs.aws.amazon.com/redshift/latest/dg/sitemap.xml
            title: Amazon Redshift Database Developer Guide
          - lang: de_de
            sitemap: https://docs.aws.amazon.com/de_de/redshift/latest/dg/sitemap.xml
            title: Datenbankentwicklerhandbuch zu Amazon Redshift
          - lang: es_es
            sitemap: https://docs.aws.amazon.com/es_es/redshift/latest/dg/sitemap.xml
            title: Guía para desarrolladores de bases de datos de Amazon Redshift
          - lang: fr_fr
            sitemap: https://docs.aws.amazon.com/fr_fr/redshift/latest/dg/sitemap.xml
            title: Guide du développeur de bases de données Amazon Redshift
          - lang: id_id
            sitemap: https://docs.aws.amazon.com/id_id/redshift/latest/dg/sitemap.xml
            title: Panduan Pengembang Database Amazon Redshift
          - lang: it_it
            sitemap: https://docs.aws.amazon.com/it_it/redshift/latest/dg/sitemap.xml
            title: Guida per sviluppatori di database di Amazon Redshift
          - lang: ja_jp
            sitemap: https://docs.aws.amazon.com/ja_jp/redshift/latest/dg/sitemap.xml
            title: Amazon Redshift データベース開発者ガイド
          - lang: ko_kr
            sitemap: https://docs.aws.amazon.com/ko_kr/redshift/latest/dg/sitemap.xml
            title: Amazon Redshift 데이터베이스 개발자 안내서
          - lang: pt_br
            sitemap: https://docs.aws.amazon.com/pt_br/redshift/latest/dg/sitemap.xml
            title: Guia do desenvolvedor de banco de dados do Amazon Redshift
          - lang: zh_cn
            sitemap: https://docs.aws.amazon.com/zh_cn/redshift/latest/dg/sitemap.xml
            title: Amazon Redshift 数据库开发人员指南
          - lang: zh_tw
            sitemap: https://docs.aws.amazon.com/zh_tw/redshift/latest/dg/sitemap.xml
            title: Amazon Redshift 資料庫開發人員指南
    permissions:
      contents: write
    uses: ./.github/workflows/download.yaml
    with:
      storage-branch: data/redshift/developer-guide/${{ matrix.lang }}
      sitemap-url: ${{ matrix.sitemap }}
      dashify-command: redshift
      docset-name: redshift-${{ matrix.lang }}
      docset-title: ${{ matrix.title }}

  create-release:
    runs-on: ubuntu-latest
    needs: download
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - id: check-artifacts
        run: |
          if ls redshift-*.tgz; then
            echo "has-artifacts=true" >> $GITHUB_OUTPUT
          else
            echo "has-artifacts=false" >> $GITHUB_OUTPUT
          fi
      - if: steps.check-artifacts.outputs.has-artifacts == 'true'
        uses: actions/checkout@v4
      - if: steps.check-artifacts.outputs.has-artifacts == 'true'
        id: version
        uses: ./.github/actions/versioning
        with:
          prefix: redshift/developer-guide/
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: steps.check-artifacts.outputs.has-artifacts == 'true'
        uses: ncipollo/release-action@v1
        id: release
        with:
          commit: data/redshift/developer-guide/en_us
          tag: redshift/developer-guide/${{ steps.version.outputs.next-version }}
          generateReleaseNotes: true
          makeLatest: false
          artifacts: redshift-*.tgz
          artifactErrorsFailBuild: true
